# https://github.com/repository-settings/app
_extends: .github
repository:
  name: standard-configs
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - Build & Lint
          - Test
      enforce_admins: true
      restrictions: null
      required_conversation_resolution: true
