# https://github.com/repository-settings/app
repository:
  name: standard-configs
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - Build & Lint
          - Test
_extends: .github
