# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: "Checks"
on: pull_request

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildAndlint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3.8.1
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - uses: actions/cache/restore@v3
        with:
          path: node_modules/.cache/turbo
          key: build-cache-${{ github.sha }}
          restore-keys: |
            build-cache-${{ github.event.pull_request.base.sha }}
      - run: npm run build
      - uses: actions/cache/save@v3
        with:
          path: node_modules/.cache/turbo
          key: build-cache-${{ github.sha }}

      - run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3.8.1
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - run: npm test
