# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: "Release"
on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v3.8.1
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - uses: actions/cache/restore@v3
        with:
          path: node_modules/.cache/turbo
          key: build-cache-${{ github.sha }}
          restore-keys: |
            build-cache-${{ github.event.before }}
      - run: npm run build
      - uses: actions/cache/save@v3
        with:
          path: node_modules/.cache/turbo
          key: build-cache-${{ github.sha }}

      - run: npm config set workspaces-update false
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx multi-semantic-release --ignore-private-packages
