# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: "Release"
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/node_modules/.cache/turbo
            ~/packages/*/.turbo
          key: build-cache
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - run: npm run build -- --force --no-cache

      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --dry-run
