# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: "Release"
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: build-cache
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - run: npm run build

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
